name: Deploy to QA
on:
  push:
    branches: ["develop"]

jobs:
  deploy-qa:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm ci

      - name: Build and Deploy (QA)
        run: |
          source /home/redmedics/.nvm/nvm.sh
          pm2 delete redmedics-server-qa || true
          npm run deploy:qa
        env:
          NODE_ENV: qa