name: Deploy to Production
on:
  push:
    branches: ["main"]

jobs:
  deploy-prod:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build and Deploy (Prod)
        run: |
          source /home/redmedics/.nvm/nvm.sh
          pm2 delete redmedics-server-prod || true  
          npm run deploy:prod
        env:
          NODE_ENV: production